CREATE TABLE Blog(
	BlogId INT NOT NULL IDENTITY(1,1),
	ApplicationUserId INT NOT NULL,
	PhotoId INT NULL,
	Title NVARCHAR(50) NOT NULL,
	Content NVARCHAR(MAX) NOT NULL,
	PublishDate DATETIME NOT NULL DEFAULT GETDATE(),
	UpdateDate DATETIME NOT NULL DEFAULT GETDATE(),
	ActiveInd BIT NOT NULL DEFAULT CONVERT(BIT,1),
	PRIMARY KEY(BlogId),
	FOREIGN KEY(ApplicationUserId) REFERENCES ApplicationUser(ApplicationUserId),
	FOREIGN KEY(PhotoId) REFERENCES Photo(PhotoId)
)